Capstone project : Crisp company website
joskalenda/crisp-coorporate-company pull request #1
Opened 2021-12-23 07:01 UTC by joskalenda

Hello there :+1: 

#### I have a great pleasure to show you this website, I worked on this Crisp company and have implemented both mobile and desktop versions using different technologies, see features below:

- Professional README file

- Check for no linter errors

- Use CSS Flex and Grid properties

- Creat feature page dynamically with JavaScript

- Deploy the Github page 

- Use CSS animation on page load

2021-12-23 13:12 UTC, moise10r requested changes
## ""Hi @joskalenda ,** 

Good job so far!

Highlight!

Good feature branch name :heavy_check_mark: 
No linter errors :heavy_check_mark: 
Descriptive commit messages :heavy_check_mark: 
Project is deployed properly :heavy_check_mark: 
Good code organization and working app :heavy_check_mark: 
 
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Suggested changes
_Check the comments under the review._

- [ ]  Recorded a video presenting the features of the project add the video link to your pull request description as required, kindly add it also to your README file to make it more descriptive.

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-12-23 13:12 UTC, moise10r commented on about.html
> +      </ul>
- [ ] Great job in the implementation of the hamburger menu, but Its background should be transparent or the same color/pattern as the top section background, Kindly change the backqround color or make it transparent.

![j1](https://user-images.githubusercontent.com/57562869/147239506-a222ceaa-65dc-4bb2-b9f1-bce5554d3cd2.png)

2021-12-23 13:12 UTC, moise10r commented on CSS/desk.css
> +  }
- [ ] There is an issue with the z-index of the ` careers-container`  class which overflow the navigation bar :point_down: 

![j2](https://user-images.githubusercontent.com/57562869/147240837-869d8a7a-1627-4b9f-92c9-ee04e110348d.png)

 I think you can fix that by adding a `z-index: -1` to your `careers--container` otherwise make sure that the container of your navigation bar has a z-index bigger than the one of `careers--container` class.

2021-12-23 13:12 UTC, moise10r commented on about.html
> +    <nav class="nav--menu">
Super cool navbar layout. Well done :+1: 
I think you missed the little navigation bar at the top. :grinning: 
Let's add it :point_down: 

 ![](https://camo.githubusercontent.com/96bd23868b8867313e32b0dd0bd61c02273f1ccfff54263caef020c9b2a779c2/68747470733a2f2f692e696d6775722e636f6d2f6e733846646b6b2e706e67)

2021-12-23 13:12 UTC, moise10r commented on CSS/style.css
> +}
![j4](https://user-images.githubusercontent.com/57562869/147243241-9fce9792-1225-4b0c-b223-3d25f88a32f8.png)
- [ ] Kindly make sure this section looks almost identical to the original design show bellow :point_down: (use the exact same colors, for text, backgrounds, borders, etc, from the original design)  you can  use `align-items: center` to center your element in the container


![44](https://user-images.githubusercontent.com/57562869/147244023-986e195d-5b87-4ab6-9f38-372f048ce89d.png)

2021-12-23 20:01 UTC, joskalenda commented
Hello Moses,
Thank you for this clear review, I really take it into consideration.

2021-12-24 06:14 UTC, moise10r approved these changes
###  **Hi @joskalenda,** 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-24 06:28 UTC, joskalenda commented
Hello Moise
Thanks for the approval

2021-12-24 06:29 UTC, merged